apiVersion: config.openshift.io/v1
kind: DpuConfig
metadata:
  labels:
    app.kubernetes.io/name: dpuconfig
    app.kubernetes.io/instance: dpuconfig-sample
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dpu-operator
  name: dpuconfig-sample
spec:
  # TODO(user): Add fields here
