clusters:
  - name : "iso_cluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    network_api_port: "eno12409"
    kind: "iso"
    install_iso: "{{iso_server()}}/RHEL-9.6.0-20241114.6-aarch64-dvd1-w-kickstart.iso.v2"
    masters:
    - name: "{{worker_number(0)}}-acc"
      node: "localhost"
      kind: "ipu"
      bmc: "{{IMC_hostname(0)}}"
      bmc_user: "root"
      bmc_password: "redhat"
      host_side_bmc: "{{bmc(0)}}"
      ip: "172.16.3.16"
      mac: "{{IPU_mac_address(0)}}"
    postconfig:
    - name: "rh_subscription"
      organization_id: "{{organization_id()}}"
      activation_key: "{{activation_key()}}"
    - name: "microshift"
    - name: "dpu_operator_dpu"
      dpu_operator_path: "../../"
      rebuild_dpu_operators_images: "true"
      ipu_plugin_sha: "e3c84b731874b10c9acf6c1b84703d4fda34901f"
      builder_image: "wsfd-advnetlab-amp04.anl.eng.bos2.dc.redhat.com:5000/ocp/builder:rhel-9-golang-1.22-openshift-4.18"
      base_image: "wsfd-advnetlab-amp04.anl.eng.bos2.dc.redhat.com:5000/ocp/4.18:base-rhel9"
