clusters:
  - name : "iso_cluster"
    api_vip: "192.168.122.99"
    ingress_vip: "192.168.122.101"
    network_api_port: "{{secondary_network_port()}}"
    kind: "iso"
    install_iso: "{{iso_server()}}/RHEL-9.6.0-20250212.4-aarch64-dvd1-w-kickstart.iso"
    masters:
    - name: "{{worker_number(0)}}-acc"
      node: "localhost"
      kind: "dpu"
      bmc:
        url: "{{bmc_hostname(0)}}"
      host_side_bmc: "{{bmc(0)}}"
      dpu_host: "{{worker_name(0)}}"
      ip: "172.16.3.16"
      mac: "{{DPU_mac_address(0)}}"
    postconfig:
    - name: "rh_subscription"
      organization_id: "{{organization_id()}}"
      activation_key: "{{activation_key()}}"
    - name: "microshift"
    - name: "dpu_operator_dpu"
      dpu_operator_path: "../../"
